### ISSUE TITLE
Final handover checklist

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#622]
Before July 31:
- [ ] All videos are on YouTube #614 #615 
- [ ] We handover word document documentation #617
- [ ] #616 
- [ ] #621
- [ ] #620
- [ ] #618
- [ ] #619

Post July 31 (when ready)
- [ ] Load and troubleshoot Spanish Language translation
- [ ] Install Spanish language on live site
